feross/buffer

index.js
e6fddaa9238c815daaf5e61d541a45bc5ef63105 handles this now, so I don't think there is any reason to keep this (from dff29085b184e9c137514b7cc2da422164e89765) hanging around.
=> remove redundant code unit size check

index.js, test/basic.js
Safari 5 does not allow setting the `constructor` property of `Uint8Array` instances. See [this demonstration][dem].
This behaivor was not being tested, but was depended on by various end-users of *buffer* (e.g., [here in *http-browserify*][ex]).
I've made the following changes:
1. Added a test for the `constructor` property getting set properly ([failed in Safari 5][sl fail]).
1. Changed `TYPED_ARRAY_SUPPORT` to be `false` if the constructor cannot get set properly, causing the object fallback to be used instead ([passed in Safari 5][sl pass]).
I ran zuul using Sauce Labs and all tests pass.
[dem]: http://i.imgur.com/ShU3Bym.png
[sl fail]: https://saucelabs.com/beta/tests/c99d86b2a82944539bbb1fe25a8506d3
[sl pass]: https://saucelabs.com/beta/tests/3c3c94eb5c9e42fcaf25e3cb275b586a
[ex]: …
=> Fix issue with setting constructor in Safari 5

index.js, test/base64.js
Using [A-z] in the regex brings in non-alphanumeric characters between the uppercase and lowercase alphabets, meaning the following chars were not correctly stripped from base 64 strings: left and right square bracket, backslash, caret, underline, and backtick. Explicitly separating the uppercase and lowercase letter ranges fixes this.
=> Fix base 64 character exclusion regex 

index.js, test/methods.js
Node.js's native Buffer module uses descending copying order in case that target buffer overlaps source buffer. This patch simulates the same behavior.
```
var b = new Buffer('abcdefghij')
b.copy(b, 3, 0, 7) // => 'abcabcdefg' but not 'abcabcabca'
```
=> descending copy from end

index.js
We are in the process of adding back the rule `padded-blocks` into `standard`. It was temporarily disabled because of a bug in eslint which now has been fixed.
This pull request makes sure that your coding style is compliant with the new version.
Please see feross/standard#170 for more info.
=> adhere to padded-blocks

index.js
Based on [a JSPerf](http://jsperf.com/string-fromcharcode-apply-vs-string-fromcharcode-using-), calling `String.fromCharCode.apply(String, array)` is indeed faster than concatenating a string in a for-loop. But of course, even slow performance is preferable to a runtime error. :)
I haven't tested to find the optimal cutoff, but 0x10000 seems like a decent size for a "large" array. For comparison, we have a test in PouchDB that puts some large PNG data into localStorage as a binary string, and in buffer v3.4.0 it was taking ~45s to run, whereas using this fix we are down to 2.7s (and it is passing, unlike v3.4.1).
=> Fix call stack exceeded in #69

index.js
Cool, that test of ours I mentioned in #70 (the "big png" test) went from 2.7s to 1.4s. Thanks @jessetane for pointing this out!
=> Improve perf of fromCharCode(), fixes #71

index.js, test/to-string.js
Noticed another inconsistency with node's Buffer - I hadn't thought about what would happen if there were already replacement chars in the utf8 we were converting!
=> utf8Slice: don't replace the replacement character

.zuul.yml, index.js, test/write.js
if the tests take too long I can set up what we do for readable-stream where each browser is it's own saucelabs test
=> fix overflow in older android

index.js, test/from-string.js
Current implementation of surrogate pair doesn't take codepoints over U+20000 into consideration. This is invalid since original specification of UTF-16 is valid until U+10FFFF.
=> Fix fatal error of surrogte pair

index.js, package.json
Because isarray is 10x more popular.
They do exactly the same thing.
`npm i browserify` for example installs them both, with this change only one is installed.
=> Use isarray instead of is-array

index.js
Adds `'strict mode'` to the beginning of `index.js`,
and makes sure that only strict-compliant operations
are used throughout the code.
This works for me in Chrome 49. Opening a pull request
to test in multiple browsers.
=> Proper strict mode support. Fixes #79

index.js
Since 1d20f50f8b4c62779c0dbfb1fa401168ab52dce0 (#40), instances already gained all the `Buffer`'s
methods via  prototype re-assignment. Skipping the `_augment`
call yields significant speedups:
+ ~50% faster small buffer creation:
+ `new(16)` before x 595,757 ops/sec ±0.92% (91 runs sampled)
+ `new(16)` after x 894,462 ops/sec ±0.69% (87 runs sampled)
+ ~20% faster slice:
+ `slice` before: 2,176,194 ops/sec ±1.59% (89 runs sampled)
+ `slice` after: 2,624,209 ops/sec ±0.42% (99 runs sampled)
Other benchmarks aren't significantly different. (These numbers are for v8.)
Also removed the similarly redundant `_isBuffer` property. In case you'd
like to keep it (even though it's private), let me know.
=> Speed up buffer creation.

index.js, test/write_infinity.js
fix for #99 to match node behavior to truncate towards ±Infinity instead of raising an exception
=> truncate toward infinity instead of raising an exception

index.js
This patch fixes the problem found on IE10 mode of IE11 developer tools.
It follows the new way to augment Uint8Array instances on typedArraySupport method.
=> re #121: IE10-on-IE11 fails the augmentation

bin/download-node-tests.js, index.js, package.json, test/node/test-buffer-alloc.js, test/node/test-buffer-arraybuffer.js, test/node/test-buffer-ascii.js, test/node/test-buffer-bad-overload.js, test/node/test-buffer-badhex.js, test/node/test-buffer-bytelength.js, test/node/test-buffer-compare-offset.js, test/node/test-buffer-concat.js, test/node/test-buffer-fill.js, test/node/test-buffer-includes.js, test/node/test-buffer-indexof.js, test/node/test-buffer-inheritance.js, test/node/test-buffer-inspect.js, test/node/test-buffer-iterator.js, test/node/test-buffer-safe-unsafe.js, test/node/test-buffer-slow.js, test/node/test-buffer-swap.js, test/node/test-buffer-zero-fill-cli.js, test/node/test-buffer-zero-fill-reset.js, test/node/test-buffer.js
There have been lots of changes to the node.js buffer tests since we last synced them. This PR brings our tests in line with what's in Node.js core. These also helped us catch several bugs in our implementation:
- Fix: treat numbers as unsigned 8-bit for .indexOf and .includes
- Fix: buffer should only be as long as the valid part of a hex string
- Add 'latin1' encoding (alias for 'binary')
- Remove deprecated 'raw' and 'raws' encoding
There are a few tests that we're still failing (but this has been the case for a while): 
- Handling invalid base64 better -- truncating the buffer at the point of the invalid data
- missing the .lastIndexOf (see #114)
The asserts that relate to the above issues remain commented out. Additionally, a stub implementation of .lastIndexOf has been added that …
=> Update node.js tests and fix the bugs it caught

bin/zuul-es5.yml, bin/zuul-es6.yml, index.js
Without this, we never go down the faster native indexOf code-path. So
this wasn't causing bugs in user code, it was just probably slower than
necessary.
=> Fix: Add missing "typeof"

index.js, test/node/test-buffer-alloc.js, test/node/test-buffer-badhex.js, test/node/test-buffer.js
- sync node.js tests to master (node v6.4.0)
- throw on negative .allocUnsafe() argument (to match new node v6.4.0 behavior)
- remove assert hack (Bug in node.js core was fixed in node v6.4.0!)
=> sync tests; throw on negative .allocUnsafe() argument; remove hacks

README.md, bin/zuul-es5.yml, index.js, package.json
Hi @feross!
The [isarray](https://www.npmjs.com/package/isarray) package [is being deprecated](https://github.com/juliangruber/isarray/issues/10) since IE < 11 is no longer supported by MS & IE 8 was the last browser that needed it. For the fringes, folks tend to use something like [es-shim](https://github.com/es-shims).
The `Array.isArray` method is supported by all Node versions, Rhino, iOS, Android, and headless browser enviros (like PhantomJS v1, SlimerJS).
With that in mind this PR removes it from `buffer`.
*Note: I don't think test fails are related to this change.*
=> Remove isarray dep.

.gitattributes, .gitignore
This updates the .gitignore to avoid the `node_modules` folder and adds a .gitattirbutes for consistent line ending handling across platforms.
=> Update dot files.

README.md
I noticed the readme still had an old browser note (those that don't support typed arrays).
=> Remove old browser note. [ci skip]

index.js
`Uint8Array` defined an unwritable `from` property, which causes overwritting operation after changing `Buffer.__proto__` fails and break script execution.
e.g. failing to assign ".from" property in **Chrome**:
When use `buffer` with webpack, everything after `Buffer.from = ...` just gone.
And e.g. failing to require `buffer` in **node@4**
We should move "Buffer.from" assignment forward to avoid this error.
Note that this may not be reproducible on all browser. In some browsers (or node@6) `Uint8Array` doesn't have 'from', or defines a writable 'from' property.
=> adventure-yunfei fix: wrong overwritting of not writable Unit8Array.from

index.js
It turns out that it's not possible to use `instanceof Buffer` safely, like I thought.
It's not possible to use `instanceof Buffer` reliably in a browserify context because there could be multiple different copies of the 'buffer' package in use.
This previous method (checking `buf._isBuffer`) works even for Buffer instances that were created from another copy of the `buffer` package.
NOTE: It's possible to have two different "instances" of the 'buffer' package, even if the 'buffer' package appears only once in the bundled code. This can happen if you require 'buffer' in different ways, for example:
`require('buffer')` vs. `require('buffer/')` vs. using the implicit `Buffer` global.
You can confirm this by browserifying this code:
```js
console.log(require('buffer').Buffer === …
```
=> Undo `instanceof Buffer` changes

README.md
Fixes: https://github.com/feross/buffer/issues/157
Also, removed `buffer-equals` from recommended list, since node 0.12 is
no longer a supported version.
=> Add conversion instructions

README.md
The .buffer property is an ArrayBuffer, but it is not necessarily the
same length as the original buffer. This adds further documentation to
the README to flesh out converting a Buffer to an ArrayBuffer.
It is based on [your answer here](https://stackoverflow.com/questions/8609289/convert-a-binary-nodejs-buffer-to-javascript-arraybuffer).
=> Add slice for converting to ArrayBuffer

index.js
Fixes: https://github.com/feross/buffer/issues/166
ArrayBuffers from another context (i.e. an iframe) do not pass the
`instanceof` check but they should be treated as valid.
=> Treat ArrayBuffers from another context as valid

bin/download-node-tests.js, index.js, package.json, test/common.js, test/node/test-buffer-alloc.js, test/node/test-buffer-arraybuffer.js, test/node/test-buffer-fill.js, test/node/test-buffer.js
This pull request updates the `test-buffer-alloc.js` from Node.js to the current upstream version.
I've used very granular commits which hopefully shows my workflow. I hope my approach is sound and the work was worth it.
This is part of #177.
=> Sync upstream test-buffer-alloc

.gitignore, .npmignore, .travis.yml, README.md, bin/airtap-es5.yml, bin/airtap-es6.yml, bin/test.js, package.json
Testing out a replacement package for zuul called airtap.
https://www.npmjs.com/package/airtap
Much simpler than zuul in that it only supports tap/tape, actively maintained, doesn't rely on the unreliable localtunnel service.
It may have big breaking changes before V1, but it's already so much more reliable that I think it's worth it.
=> Replace zuul with airtap

index.js
This is benign due to the module nature, but just for consistency.
Noticed while doing a global code search ;-).
Note: I have not tested this, but should be fine. Placing hopes in the CI ;-).
=> new Buffer -> Buffer.from

bin/test.js
Rely on airtap to automatically skip browser tests when Travis secure variables are not available (in PRs)
=> airtap: always run browser test

index.js
Running under [Secure EcmaScript (SES)](https://github.com/Agoric/SES), setting prototype via `__proto__` is disabled. This causes `Buffer` to fail.
Setting the prototype via `Object.setPrototypeOf` works correctly under SES.
According to the comments, different environments have strange behavior regarding `TypedArray` and setting prototypes, and I'm not sure if this method will work correctly in those environments.
[Here is the compat table][compat-table] for `Object.setPrototypeOf`
[compat-table]: https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.setPrototypeOf_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_wid …
=> use "Object.setPrototypeOf" instead of "__proto__"

index.js
Lookup table faster ~9-12 times than toString('hex') for each byte. See https://github.com/feross/buffer/issues/219
<hr>
Benchmarks for generating lookup table:
<details>
<summary>code here</summary>
```js
function g11 () {
var table = []
for (var i = 0; i < 256; ++i) {
table[i] = ('0' + i.toString(16)).slice(-2)
}
return table
}
function g12 () {
var table = []
for (var i = 0; i < 256; ++i) {
table.push(('0' + i.toString(16)).slice(-2))
}
return table
}
function g13 () {
var table = new Array(256)
for (var i = 0; i < 256; ++i) {
table[i] = ('0' + i.toString(16)).slice(-2)
}
return table
}
function g211 () {
var alphabet = '0123456789abcdef'
var table = []
for (var i = 0; i < 16; ++i) {
for (var j = 0; j < 16; ++j) {
table[i * 16 + j] = alphabet[i] + alphabet[j]
}
}
return table
} …
```
=> Use lookup table for faster hex encoding

index.js, package.json, test/node/test-buffer-alloc.js
Closes https://github.com/feross/buffer/issues/256
`SharedArrayBuffer` has the same properties as `ArrayBuffer` (`new Uint8Array(sab)` works, `sab.byteLength` exists), therefore `fromArrayBuffer` can be used.
=> Fix Buffer.from for SharedArrayBuffer

index.js
We now handle calls like:
new Buffer(arraybuffer, 2, 8) so there's no need for this workaround originally implemented in: https://github.com/feross/buffer/pull/97
More info: https://bugs.chromium.org/p/v8/issues/detail?id=4665#c4
Fixes #260. Supersedes #261
=> Remove unneeded Symbol.species code

index.js
Hello!
It looks like the function isn't needed. Am I missing something?
=> remove redundant latin1Write function

index.js
For example, Opera 10.6.
Introduced in #204; affects v5.4.0+.
=> [Fix] `Symbol.for` is a syntax error in older browsers

index.js, test/to-string.js
```js
const oddLengthBuffer = Buffer.from('abcde', 'utf8')
console.log(Buffer.from(oddLengthBuffer.toString('utf16le'), 'utf16le').toString('utf8')) // ‘abcd’ in Node.js and ‘abcd\x00\x00’ with polyfill
```
This comes from accessing n+1-th element of a Buffer of size n in utf16leSlice.
We omit the last byte for an odd length buffer when encoding to UTF16-LE
=> Different behaviour from node.js for utf16leSlice

index.js
Uint8Array.prototype.set handles overlapping ranges on its own.
=> Remove descending copy from end

index.js, package.json, test/node/test-buffer-bigint64.js
This PR is extension of PR #247 by @fanatid. 
It addresses the issue described in https://github.com/feross/buffer/pull/247#issuecomment-645646172
=> Add RW BigInt64 methods

index.d.ts
The API supports at various places to use Uint8Arrays to be used instead of Buffers. This PR loosens the type restrictions on a few instances where I noticed that an Uint8Array would suffice.
=> Types: Using Uint8Array instead of Buffer

index.d.ts
=> Redefined subarray in index.d.ts to return Buffer

README.md
This change replaces "a sanity check" with "an additional check."
Justification:
> The phrase sanity check is ableist, and unnecessarily references mental health in our code bases. It denotes that people with mental illnesses are inferior, wrong, or incorrect, and the phrase sanity continues to be used by employers and other individuals to discriminate against these people.
Via [Ableist language](https://gist.github.com/seanmhanson/fe370c2d8bd2b3228680e38899baf5cc#:~:text=The%20phrase%20sanity%20check%20is,to%20discriminate%20against%20these%20people.)
See also: [Google developer documentation style guide: Writing inclusive documentation](https://developers.google.com/style/inclusive-documentation)
=> Updates README.md with more inclusive language

index.js, test/node/test-buffer.js
add missing kStringMaxLength, constants.MAX_LENGTH & constants.MAX_STRING_LENGTH
fixes #311
=> add missing constants

package.json
Follow up to https://github.com/feross/buffer/pull/331
`standard` was in the `test` target, which I think is misleading when we can differentiate that in the GitHub pull requests using workflows (as I did in https://github.com/feross/buffer/pull/331).
Additionally, our default `test` should prioritise `node` for now, until I can update the CI with an alternative to `airtap` (or at least, fix `airtap`) for browser testing (our primary priority and userbase).
=> Remove standard from tests, prefer node testing for first-pass CI

test/node/test-buffer-badhex.js
Fixes the failing tests introduced in #303. Since the `Buffer` was 4 bytes long these comparisons couldn't ever work before.
=> Fix failing tests for #303 (unreleased)

index.js, package.json, perf/write-hex.js, test/write-hex.js
Should fix the slowdown introduced by the hash table lookups in #303
My own benchmarks seem to indicate a 10x speedup.
=> Optimize hexWrite with an array lookup table

index.js
=> Remove class syntax for better babelification (2)

index.js, test/typing.js
Logic behind this:
1. `b instanceof Uint8Array` always returns true for Buffers created in the same context.
2. `ArrayBuffer.isView(b)` returns true for both Uint8Arrays and Buffers created in __any__ context (at least in v8 -- hopefully other browsers too).
3. `isInstance(b, Uint8Array)` returns true for Uint8rrays created in __any__ context but currently only returns true for Buffers created in the __same__ context.
Number 3 has an inconsistency. This PR seeks to rectify that and also optimize several functions in doing so.
If we modify the code such that `isInstance(b, Uint8Array)` returns true for Buffers created in __all__ contexts, we can drop a ton of the "buffer casting" for Uint8Arrays (which in most cases is actually entirely redundant and causes a slowdown -- for example, in …
=> Fix issues surrounding type checking for Uint8Arrays and Buffers

index.js
A more cautious approach than the one in #347.
=> Remove `global` accesses

LICENSE
Should cover any node.js code we decide to re-use (primarily for `test/node` right now).
=> Add node.js attribution to LICENSE

package.json
GitHub hasn't supported the git protocol [since 2022](https://github.blog/security/application-security/improving-git-protocol-security-github/#no-more-unauthenticated-git), so this URL is broken.
(This is a common error affecting many popular npm packages; I'm opening PRs on several projects to fix it. I encourage anyone reading this to check any packages they maintain and implement the same fix if appropriate!)
=> Fix broken repository URL in package.json
